fix

diff --git a/cdh4.1/bin/go b/cdh4.1/bin/go
--- a/cdh4.1/bin/go
+++ b/cdh4.1/bin/go
@@ -7,7 +7,7 @@ if [ $# != 1 ]; then
   exit 1;
 fi
 
-[ -z $DEPLOYER_HOME ] && echo "deployer hasn't install or install fail" && exit 1;
-. $DEPLOYER_HOME/support/PUB.sh;
+[ -z $DP_HOME ] && echo "deployer hasn't install or install fail" && exit 1;
+. $DP_HOME/support/PUB.sh;
 
 ssh $1
diff --git a/cdh4.1/bin/otherdo b/cdh4.1/bin/otherdo
--- a/cdh4.1/bin/otherdo
+++ b/cdh4.1/bin/otherdo
@@ -8,8 +8,8 @@ if [ $# -le 0 ]; then
   exit 1
 fi
 
-[ -z $DEPLOYER_HOME ] && echo "deployer hasn't install or install fail" && exit 1;
-. $DEPLOYER_HOME/support/PUB.sh;
+[ -z $DP_HOME ] && echo "deployer hasn't install or install fail" && exit 1;
+. $DP_HOME/support/PUB.sh;
 
 . $D/config_deployer.sh
 
